version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: section6
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  # stripe-cli:
  #   image: stripe/stripe-cli
  #   container_name: stripe-cli
  #   command: ["listen", "-H", "x-djstripe-webhook-secret: whsec_******", "--forward-to", "http://host.docker.internal:3000/api/webhooks"]
  #   env_file:
  #     - ./client/.env

volumes:
  postgres_data:
  pgadmin_data: